# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20161209_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.TextField(default='...', max_length=32, verbose_name='简介'),
        ),
    ]
