# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20161209_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='data',
        ),
        migrations.AddField(
            model_name='paint',
            name='image',
            field=models.ImageField(default=False, upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
