# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0007_auto_20170102_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length='256', verbose_name='内容')),
                ('type', models.IntegerField(choices=[(0, '评论'), (1, '消息'), (2, '@'), (3, '喜欢')], verbose_name='类型')),
            ],
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ('-pub_date',), 'verbose_name': '挑战', 'verbose_name_plural': '挑战'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='paint',
            options={'ordering': ('-pub_date',), 'verbose_name': '画', 'verbose_name_plural': '画'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': '粉丝关系', 'verbose_name_plural': '粉丝关系'},
        ),
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.Comment'),
        ),
        migrations.AddField(
            model_name='message',
            name='paint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.Paint'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
