# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_auto_20170103_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, '评论'), (1, '消息'), (2, '@'), (3, '喜欢'), (4, '关注')], verbose_name='类型'),
        ),
    ]
